---
- include:              '../tasks/install_packages.yml'
- include:              '../tasks/install_package_files.yml'
- include:              '../tasks/shell_commands_ignore_result.yml'
- include:              '../tasks/create_files.yml'
- include:              '../tasks/template_files.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/symlinks.yml'
- include:              '../tasks/restart_services.yml'
  when:                 install_packages_result.changed
                        or install_package_files_result.changed
                        or create_files_result.changed
                        or template_files_result.changed
                        or install_files_result.changed 
                        or symlinks_result.changed
- include:              '../tasks/enable_services.yml'
- include:              '../tasks/start_services.yml'
